#!/usr/bin/env node
import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, '..')
const deployScript = path.join(repoRoot, 'scripts', 'esp32s3-touch-amoled-2.06.sh')
const targetDir = path.join(repoRoot, 'targets', 'esp32-s3-touch-amoled-2.06')
const partitionsPath = path.join(targetDir, 'partitions.csv')
const buildImagePath = path.join(targetDir, 'build', 'gea_embedded.bin')

const launcherId = 'app-launcher'
const firstAppOffset = 0x20000
const bootableAppRegionEnd = 0x2000000
const appAlignment = 0x10000
const firmwareOtaSlotCount = 2

function usage() {
  console.log(`Usage:
  npm run format-apps [-- --port=<port>]
  npm run format-apps -- --ota=<board-ip>

Examples:
  npm run format-apps
  npm run format-apps -- --port=/dev/cu.usbmodem101
  npm run format-apps -- --ota=192.168.1.42
  npm run format-apps -- --dry-run

Options:
  --port=<port>   USB serial port. Defaults to auto-detect.
  --ota=<target>  Erase legacy non-launcher app slots over WiFi OTA.
  --dry-run       Print the format plan without flashing or erasing.
`)
}

function parseArgs(argv) {
  let port = 'auto'
  let otaTarget = ''
  let dryRun = false

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === '--dry-run') {
      dryRun = true
    } else if (arg === '--port') {
      i += 1
      if (!argv[i]) throw new Error('Missing value after --port')
      port = argv[i]
    } else if (arg.startsWith('--port=')) {
      port = arg.slice('--port='.length)
    } else if (arg === '--ota' || arg === '--host' || arg === '--ip') {
      i += 1
      if (!argv[i]) throw new Error(`Missing value after ${arg}`)
      otaTarget = argv[i]
    } else if (arg.startsWith('--ota=')) {
      otaTarget = arg.slice('--ota='.length)
    } else if (arg.startsWith('--host=')) {
      otaTarget = arg.slice('--host='.length)
    } else if (arg.startsWith('--ip=')) {
      otaTarget = arg.slice('--ip='.length)
    } else if (arg === '--help' || arg === '-h') {
      usage()
      process.exit(0)
    } else {
      throw new Error(`Unknown argument: ${arg}`)
    }
  }

  if (otaTarget && port !== 'auto') {
    throw new Error('--port is for USB format. Use --ota=<board-ip> for WiFi OTA format.')
  }

  return { port, otaTarget, dryRun }
}

function hex(value) {
  return `0x${value.toString(16)}`
}

function alignDown(value, alignment) {
  return Math.floor(value / alignment) * alignment
}

function buildLauncherOnlyPartitionTable() {
  const slotSize = alignDown(Math.floor((bootableAppRegionEnd - firstAppOffset) / firmwareOtaSlotCount), appAlignment)
  const lines = [
    '# Generated by npm run format-apps. Safe to regenerate.',
    `# Installed app plan: ${launcherId}`,
    '# Resident app plan: <none>',
    '# Firmware OTA layout: app-launcher plus one regular OTA update slot',
    '# Name,    Type, SubType, Offset,   Size',
    `# ota_0: ${launcherId}`,
    `# ota_1: ${launcherId}`,
    'nvs,       data, nvs,     0x9000,   0x6000',
    'otadata,   data, ota,     0xf000,   0x2000',
    'phy_init,  data, phy,     0x11000,  0x1000',
  ]

  for (let slot = 0; slot < firmwareOtaSlotCount; slot += 1) {
    const name = `ota_${slot}`
    const offset = firstAppOffset + slot * slotSize
    lines.push(`${`${name},`.padEnd(10)} app,  ${`${name},`.padEnd(8)} ${`${hex(offset)},`.padEnd(9)} ${hex(slotSize)}`)
  }

  return {
    csv: `${lines.join('\n')}\n`,
    slotSize
  }
}

function run(command, args, options = {}) {
  console.log(`\n$ ${[command, ...args].join(' ')}`)
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    stdio: 'inherit',
    shell: false,
    ...options
  })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}

function otaBaseUrl(target) {
  const trimmed = target.replace(/\/+$/, '')
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) return trimmed
  if (trimmed.includes(':')) return `http://${trimmed}`
  return `http://${trimmed}:8080`
}

async function readOtaStatus(target) {
  const url = `${otaBaseUrl(target)}/ota/status`
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${url} returned HTTP ${response.status}`)
  return response.json()
}

function formatOverUsb(port, dryRun) {
  const { csv, slotSize } = buildLauncherOnlyPartitionTable()
  console.log('Formatting launcher apps over USB')
  console.log(`New plan: ${launcherId}`)
  console.log(`Launcher slot size: ${hex(slotSize)} (${Math.floor(slotSize / 1024)} KiB)`)

  if (dryRun) {
    console.log('\nGenerated partition table:\n')
    console.log(csv)
    return
  }

  writeFileSync(partitionsPath, csv)
  console.log(`\nWrote ${path.relative(repoRoot, partitionsPath)}`)
  run(deployScript, ['build', `--app=${launcherId}`, `--resident-apps=${launcherId}`])
  run(deployScript, [
    'flash-image',
    port,
    `--app=${launcherId}`,
    `--image=${buildImagePath}`
  ])
  console.log('\nFormat complete. Launcher firmware is in ota_0, with ota_1 reserved for OTA updates.')
}

async function formatOverOta(otaTarget, dryRun) {
  if (dryRun) {
    console.log(`Formatting launcher apps over WiFi OTA from ${otaBaseUrl(otaTarget)}`)
    console.log('Would query /ota/status and erase every legacy non-launcher, non-running app slot. Use USB format once to apply the two-slot partition table.')
    return
  }

  const status = await readOtaStatus(otaTarget).catch(error => {
    throw new Error(`Could not read OTA status from ${otaBaseUrl(otaTarget)}. Make sure the board is running current firmware with /ota/status support. ${error.message}`)
  })

  const runningLabel = status.running && status.running.label ? status.running.label : ''
  const erasable = (status.partitions || []).filter(partition =>
    partition.label !== runningLabel && partition.version !== launcherId
  )

  console.log(`Formatting launcher apps over WiFi OTA from ${otaBaseUrl(otaTarget)}`)
  console.log('OTA format cannot rewrite the partition table; use USB format once to apply the two-slot launcher layout.')
  if (erasable.length === 0) {
    console.log('No non-launcher app slots are erasable right now.')
    if (runningLabel) console.log(`Running slot kept: ${runningLabel}`)
    return
  }

  for (const partition of erasable) {
    console.log(`  erase ${partition.label.padEnd(6)} ${partition.version || '<empty>'}`)
    run(deployScript, ['erase-slot-ota', otaTarget, `--slot=${partition.label}`])
  }

  if (runningLabel) {
    console.log(`Kept running slot: ${runningLabel}`)
  }
}

async function main() {
  const { port, otaTarget, dryRun } = parseArgs(process.argv.slice(2))
  if (otaTarget) {
    await formatOverOta(otaTarget, dryRun)
  } else {
    formatOverUsb(port, dryRun)
  }
}

main().catch(error => {
  console.error(`ERROR: ${error.message}`)
  process.exit(1)
})
